# Bài 3: Đọc và lọc dữ liệu

In [1]:
import pandas as pd

fruit = pd.Series(['apple', 'banana', 'orange'], index=['A', "B", 'C'])
fruit

A     apple
B    banana
C    orange
dtype: object

In [2]:
# Khởi tạo Series từ 1 Dict
dog_dict={
    "A": 'Husky',
    'B': "Chihuahua",
    'C': "Inushiba"
}

dog_series = pd.Series(dog_dict)
dog_series

A        Husky
B    Chihuahua
C     Inushiba
dtype: object

### Bài thực hành 1: 
mean: Tính tổng các phần tử sau đó chia cho số phần tử
median: Sắp xếp mảng và tìm phần tử ở giữa
mode: Phần tử xuất hiện nhiều lần nhất

In [3]:
weights = pd.Series([37, 48, 42, 39, 100], index=["Hoa", "Nam", "Hải", 'Linh', 'Nhân']) 
print(weights.mean())
print(weights.median())
print(weights.mode())

53.2
42.0
0     37
1     39
2     42
3     48
4    100
dtype: int64

### DATAFRAME
- DF > S
- Mỗi cột trong DF là 1 S

In [4]:
animals = pd.DataFrame({ # giống với ctdl: dictinary
    "dong_vat": ["Sao la", 'Khỉ đuôi ngắn', 'Voi châu Á'],
    "tuoi_tho": [25, 25, 70],
    "loai": ["có vú", 'linh trưởng', 'có vú']
})

animals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   dong_vat  3 non-null      object
 1   tuoi_tho  3 non-null      int64
 2   loai      3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [5]:
animals.to_csv('./animals.csv',index=False) # lệnh tạo file CSV thông qua DF

### Đọc file với lệnh read_csv()

In [6]:
df_read = pd.read_csv("./animals.csv")
df_read

# Lựa chọn hàng sử dụng ngoặc vuông
df_read[:2] # Lấy từ vị trí đầu tiến đến 2-1
# df_read[2:] # Lấy từ vị trí thứ 2 đến hết.

        dong_vat  tuoi_tho         loai
0         Sao la        25        có vú
1  Khỉ đuôi ngắn        25  linh trưởng

In [7]:
# Lựa chọn một cột sử dụng ngoặc vuông
df_read["loai"]

0          có vú
1    linh trưởng
2          có vú
Name: loai, dtype: object

In [8]:
# Lựa chọn nhiều cột -> Sử dụng danh sách các cột
df_read[["dong_vat", 'tuoi_tho']] # Chỉ lấy 2 cột được chọn, không lấy cột còn lại.

        dong_vat  tuoi_tho
0         Sao la        25
1  Khỉ đuôi ngắn        25
2     Voi châu Á        70

In [9]:
## Yêu cầu: Lấy ra động vật nào có tuổi thọ < 30
age_data = df_read[["dong_vat", 'tuoi_tho']]
age_data[df_read["tuoi_tho"] < 30] # thỏa mãn yêu cầu đề bài

        dong_vat  tuoi_tho
0         Sao la        25
1  Khỉ đuôi ngắn        25

In [10]:
# Chọn một cột trong DF là "key" (index: mặc định là 0, 1, 2,...)
# df_read.set_index("dong_vat", inplace=True) # chọn cột dong_vat => làm khóa của DF.

# df_read

In [11]:
## Nếu không muốn cột nào làm chỉ số (index) => reset index
df_read.reset_index()

   index       dong_vat  tuoi_tho         loai
0      0         Sao la        25        có vú
1      1  Khỉ đuôi ngắn        25  linh trưởng
2      2     Voi châu Á        70        có vú

### LỌC BẰNG CHỈ SỐ: ILOC
- Lọc dữ liệu dựa trên vị trí chỉ số trong DF

In [12]:
df_read.reset_index()
df_read.iloc[:2, 1:3]

   tuoi_tho         loai
0        25        có vú
1        25  linh trưởng

In [13]:
## Lọc bằng nhãn: loc - lọc dữ liệu dựa trên nhãn chỉ số
# df_read.loc[df_read["tuoi_tho"] > 30] # Lấy ra dữ liệu thỏa mãn điều kiện (dựa trên nhãn)
# df_read.loc[df_read["loai"] == "có vú"] # Lấy ra dữ liệu thỏa mãn điều kiện (dựa trên nhãn)
df_read.loc[df_read["tuoi_tho"] > 50, "tuoi_tho":"loai"] # Lấy ra dữ liệu thỏa mãn điều kiện (dựa trên nhãn)

   tuoi_tho   loai
2        70  có vú